/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyoutfitıdeassys;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import easyoutfitıdeas.model.sensor;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Sony
 */
public class oneri extends javax.swing.JFrame {
    
    private boolean sensor;
public void oneriListele() throws SQLException{
        DbConnection db=new DbConnection();
        List<sensor> ls = new ArrayList<>();
        ls = db.sensor_listele();
        String sonuc = "";
       
            String element = ls.get(5).getSicaklik();
            int x = Character.getNumericValue(element.charAt(3));
        
        System.out.println(x);
           if (x<0){
                sonuc = "Oneri: Çok kalın giyin. ";
            }
           else if(x>0 && x<=10){
                sonuc =   "Oneri: Kalın giyin.";
            }
           else if(x>10 && x<=20){
                sonuc="Oneri: Normal giyinebilirsin. ";
            }
           else{
               sonuc="Oneri: Ince birseyler giysen yeterli.";
    
            }
       
          
        
        txt_oneri.setText(sonuc);
   
        
    }
   
    
    public oneri() throws SQLException {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("java.png")));
       oneriListele();
    }
    public Eos_main parent;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_oneri = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_oneri.setColumns(20);
        txt_oneri.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        txt_oneri.setRows(5);
        txt_oneri.setPreferredSize(new java.awt.Dimension(800, 400));
        jScrollPane1.setViewportView(txt_oneri);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oneri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oneri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oneri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oneri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    /*    JScrollPane scrollPane = new JScrollPane(tb);
                    new sensor_listele().add(scrollPane, BorderLayout.CENTER);
                    new sensor_listele().setSize(300, 150); */
                    new oneri().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(sensor_listele.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_oneri;
    // End of variables declaration//GEN-END:variables
}
